import type { KidWord } from "./words";

type AnimalWord = [word: string, thai: string, category: string];

const animalWords: AnimalWord[] = [
  ["aardvark", "อาร์ดวาร์ก", "animal"],
  ["alpaca", "อัลปากา", "animal"],
  ["badger", "แบดเจอร์", "animal"],
  ["beaver", "บีเวอร์", "animal"],
  ["bison", "ไบซัน", "animal"],
  ["bobcat", "บ็อบแคต", "animal"],
  ["buffalo", "ควาย", "animal"],
  ["caracal", "คาราคัล", "animal"],
  ["cheetah", "ชีตาห์", "animal"],
  ["cougar", "คูการ์", "animal"],
  ["coyote", "โคโยตี้", "animal"],
  ["dingo", "ดิงโก", "animal"],
  ["ferret", "เฟอร์เร็ต", "animal"],
  ["gazelle", "กาเซลล์", "animal"],
  ["gerbil", "เจอร์บิล", "animal"],
  ["gibbon", "ชะนี", "animal"],
  ["hamster", "แฮมสเตอร์", "animal"],
  ["hyena", "ไฮยีนา", "animal"],
  ["jackal", "หมาใน", "animal"],
  ["jaguar", "จากัวร์", "animal"],
  ["lemur", "ลีเมอร์", "animal"],
  ["llama", "ลามา", "animal"],
  ["lynx", "ลิงซ์", "animal"],
  ["meerkat", "เมียร์แคต", "animal"],
  ["mink", "มิงก์", "animal"],
  ["mole", "ตุ่น", "animal"],
  ["mongoose", "พังพอน", "animal"],
  ["moose", "มูส", "animal"],
  ["ocelot", "โอเซล็อต", "animal"],
  ["okapi", "โอคาปี", "animal"],
  ["opossum", "โอพอสซัม", "animal"],
  ["panther", "แพนเธอร์", "animal"],
  ["pangolin", "ลิ่น", "animal"],
  ["platypus", "ตุ่นปากเป็ด", "animal"],
  ["porcupine", "เม่น", "animal"],
  ["quokka", "ควอกกา", "animal"],
  ["raccoon", "แรคคูน", "animal"],
  ["reindeer", "กวางเรนเดียร์", "animal"],
  ["serval", "เซอร์วัล", "animal"],
  ["skunk", "สกังก์", "animal"],
  ["tapir", "สมเสร็จ", "animal"],
  ["wallaby", "วอลลาบี", "animal"],
  ["weasel", "วีเซิล", "animal"],
  ["wombat", "วอมแบต", "animal"],
  ["yak", "จามรี", "animal"],
  ["baboon", "บาบูน", "monkey"],
  ["capuchin", "คาปูชิน", "monkey"],
  ["chimp", "ชิมแปนซี", "monkey"],
  ["macaque", "ลิงแสม", "monkey"],
  ["mandrill", "แมนดริล", "monkey"],
  ["marmoset", "มาร์โมเซต", "monkey"],
  ["orangutan", "อุรังอุตัง", "monkey"],
  ["tamarin", "ทามาริน", "monkey"],
  ["budgie", "นกหงส์หยก", "bird"],
  ["canary", "นกคีรีบูน", "bird"],
  ["cardinal", "นกคาร์ดินัล", "bird"],
  ["condor", "แร้งคอนดอร์", "bird"],
  ["crow", "กา", "bird"],
  ["dove", "นกพิราบขาว", "bird"],
  ["eagle", "นกอินทรี", "bird"],
  ["emu", "นกอีมู", "bird"],
  ["falcon", "เหยี่ยว", "bird"],
  ["finch", "นกฟินช์", "bird"],
  ["flamingo", "นกฟลามิงโก", "bird"],
  ["goose", "ห่าน", "bird"],
  ["gull", "นกนางนวล", "bird"],
  ["hawk", "เหยี่ยว", "bird"],
  ["heron", "นกกระสา", "bird"],
  ["kiwi", "นกกีวี", "bird"],
  ["magpie", "นกแมกพาย", "bird"],
  ["ostrich", "นกกระจอกเทศ", "bird"],
  ["pelican", "นกกระทุง", "bird"],
  ["pigeon", "นกพิราบ", "bird"],
  ["puffin", "นกพัฟฟิน", "bird"],
  ["raven", "นกเรเวน", "bird"],
  ["robin", "นกโรบิน", "bird"],
  ["sparrow", "นกกระจอก", "bird"],
  ["stork", "นกกระสา", "bird"],
  ["swallow", "นกนางแอ่น", "bird"],
  ["toucan", "นกทูแคน", "bird"],
  ["woodpecker", "นกหัวขวาน", "bird"],
  ["albatross", "นกอัลบาทรอส", "bird"],
  ["bluejay", "นกบลูเจย์", "bird"],
  ["cockatoo", "นกค็อกคาทู", "bird"],
  ["crane", "นกกระเรียน", "bird"],
  ["cuckoo", "นกคัคคู", "bird"],
  ["duckling", "ลูกเป็ด", "bird"],
  ["egret", "นกยาง", "bird"],
  ["grouse", "ไก่ป่า", "bird"],
  ["kingfisher", "นกกระเต็น", "bird"],
  ["loon", "นกลูน", "bird"],
  ["macaw", "นกมาคอว์", "bird"],
  ["mynah", "นกขุนทอง", "bird"],
  ["oriole", "นกขมิ้น", "bird"],
  ["quail", "นกกระทา", "bird"],
  ["tern", "นกนางนวลแกลบ", "bird"],
  ["vulture", "แร้ง", "bird"],
  ["anchovy", "ปลาแอนโชวี", "fish"],
  ["angelfish", "ปลาเทวดา", "fish"],
  ["bass", "ปลากะพง", "fish"],
  ["betta", "ปลากัด", "fish"],
  ["carp", "ปลาคาร์ป", "fish"],
  ["catfish", "ปลาดุก", "fish"],
  ["clownfish", "ปลาการ์ตูน", "fish"],
  ["cod", "ปลาค็อด", "fish"],
  ["flounder", "ปลาลิ้นหมา", "fish"],
  ["goldfish", "ปลาทอง", "fish"],
  ["guppy", "ปลาหางนกยูง", "fish"],
  ["halibut", "ปลาฮาลิบัต", "fish"],
  ["herring", "ปลาเฮร์ริง", "fish"],
  ["koi", "ปลาคาร์ป", "fish"],
  ["mackerel", "ปลาแมกเคอเรล", "fish"],
  ["marlin", "ปลามาร์ลิน", "fish"],
  ["minnow", "ปลาซิว", "fish"],
  ["piranha", "ปลาปิรันยา", "fish"],
  ["puffer", "ปลาปักเป้า", "fish"],
  ["salmon", "ปลาแซลมอน", "fish"],
  ["sardine", "ปลาซาร์ดีน", "fish"],
  ["swordfish", "ปลากระโทง", "fish"],
  ["trout", "ปลาเทราต์", "fish"],
  ["tuna", "ปลาทูน่า", "fish"],
  ["barracuda", "ปลาสาก", "fish"],
  ["bluegill", "ปลาบลูกิลล์", "fish"],
  ["bonito", "ปลาโอ", "fish"],
  ["goby", "ปลาบู่", "fish"],
  ["grouper", "ปลาเก๋า", "fish"],
  ["haddock", "ปลาแฮดด็อก", "fish"],
  ["lionfish", "ปลาสิงโต", "fish"],
  ["manta", "กระเบนราหู", "fish"],
  ["molly", "ปลามอลลี่", "fish"],
  ["perch", "ปลาเพิร์ช", "fish"],
  ["sawfish", "ปลาฉนาก", "fish"],
  ["snapper", "ปลากะพงแดง", "fish"],
  ["sole", "ปลาตาเดียว", "fish"],
  ["stingray", "ปลากระเบน", "fish"],
  ["sunfish", "ปลาแสงอาทิตย์", "fish"],
  ["tetra", "ปลาเตตรา", "fish"],
  ["crayfish", "กุ้งเครย์ฟิช", "sea animal"],
  ["krill", "เคย", "sea animal"],
  ["mussel", "หอยแมลงภู่", "sea animal"],
  ["nautilus", "นอติลุส", "sea animal"],
  ["oyster", "หอยนางรม", "sea animal"],
  ["scallop", "หอยเชลล์", "sea animal"],
  ["sponge", "ฟองน้ำทะเล", "sea animal"],
  ["urchin", "เม่นทะเล", "sea animal"],
  ["orca", "วาฬเพชฌฆาต", "sea animal"],
  ["manatee", "พะยูน", "sea animal"],
  ["walrus", "วอลรัส", "sea animal"],
  ["barnacle", "เพรียง", "sea animal"],
  ["limpet", "หอยหมวก", "sea animal"],
  ["sea slug", "ทากทะเล", "sea animal"],
  ["sea lion", "สิงโตทะเล", "sea animal"],
  ["mantis", "ตั๊กแตนตำข้าว", "bug"],
  ["cicada", "จักจั่น", "bug"],
  ["cricket", "จิ้งหรีด", "bug"],
  ["flea", "หมัด", "bug"],
  ["gnat", "ริ้น", "bug"],
  ["grasshopper", "ตั๊กแตน", "bug"],
  ["hornet", "แตน", "bug"],
  ["moth", "ผีเสื้อกลางคืน", "bug"],
  ["roach", "แมลงสาบ", "bug"],
  ["termite", "ปลวก", "bug"],
  ["wasp", "ตัวต่อ", "bug"],
  ["centipede", "ตะขาบ", "bug"],
  ["millipede", "กิ้งกือ", "bug"],
  ["scorpion", "แมงป่อง", "bug"],
  ["tick", "เห็บ", "bug"],
  ["axolotl", "แอกโซลอเติล", "weird animal"],
  ["echidna", "อีคิดนา", "weird animal"],
  ["frilled", "กิ้งก่าคอจีบ", "weird animal"],
  ["narwhal", "นาร์วาล", "weird animal"],
  ["okapi", "โอคาปี", "weird animal"],
  ["quoll", "ควอลล์", "weird animal"],
  ["aye-aye", "อายอาย", "weird animal"],
  ["cassowary", "แคสโซวารี", "weird animal"],
  ["thorny", "กิ้งก่าหนาม", "weird animal"],
  ["tarsier", "ทาร์เซียร์", "weird animal"],
  ["agama", "กิ้งก่าอะกามา", "reptile"],
  ["boa", "งูเหลือม", "reptile"],
  ["caiman", "เคแมน", "reptile"],
  ["cobra", "งูเห่า", "reptile"],
  ["crocodile", "จระเข้", "reptile"],
  ["newt", "นิวต์", "amphibian"],
  ["python", "งูหลาม", "reptile"],
  ["salamander", "ซาลาแมนเดอร์", "amphibian"],
  ["viper", "งูไวเปอร์", "reptile"],
  ["velociraptor", "เวโลซิแรปเตอร์", "dinosaur"],
  ["allosaurus", "อัลโลซอรัส", "dinosaur"],
  ["ankylosaur", "แองคิโลซอรัส", "dinosaur"],
  ["apatosaurus", "อะพาโทซอรัส", "dinosaur"],
  ["brachiosaur", "แบรคิโอซอรัส", "dinosaur"],
  ["diplodocus", "ดิพโลโดคัส", "dinosaur"],
  ["iguanodon", "อิกัวโนดอน", "dinosaur"],
  ["parasaur", "พาราซอร์", "dinosaur"],
  ["pteranodon", "เทอราโนดอน", "dinosaur"],
  ["spinosaurus", "สไปโนซอรัส", "dinosaur"],
  ["carnotaurus", "คาร์โนทอรัส", "dinosaur"],
  ["ceratosaur", "เซราโตซอรัส", "dinosaur"],
  ["compy", "คอมปี", "dinosaur"],
  ["dilophosaur", "ไดโลโฟซอรัส", "dinosaur"],
  ["giganotosaur", "กิกาโนโตซอรัส", "dinosaur"],
  ["mosasaur", "โมซาซอร์", "dinosaur"],
  ["oviraptor", "โอวิแรปเตอร์", "dinosaur"],
  ["pachy", "แพคี", "dinosaur"],
  ["sauropod", "ซอโรพอด", "dinosaur"]
];

const clean = (value: string) => value.toLowerCase().replace(/[^a-z]/g, "");

function makeHints(word: string): string[] {
  const compact = clean(word);
  const hints = new Set<string>([compact]);
  if (compact.length > 2) hints.add(compact.slice(0, -1));
  if (compact.length > 3) hints.add(compact.slice(1));
  return [...hints].slice(0, 5);
}

export function buildAnimalWords(): KidWord[] {
  return animalWords.map(([word, thai, category]) => ({
    word,
    thai,
    emoji: "?",
    tier: "kid",
    priority: 0.1,
    hints: makeHints(word),
    imagePrompt: `clear child-friendly flashcard image of ${word}, ${category}, cute but recognizable, centered on transparent background`
  }));
}
