import type { KidWord } from "./words";

type RawWord = [word: string, thai: string, emoji: string, category: string];

const rawWords: RawWord[] = [
  ["baby", "เด็กเล็ก", "👶", "people"],
  ["child", "เด็ก", "🧒", "people"],
  ["kid", "เด็ก", "🧒", "people"],
  ["girl", "เด็กผู้หญิง", "👧", "people"],
  ["boy", "เด็กผู้ชาย", "👦", "people"],
  ["mom", "แม่", "👩", "people"],
  ["mother", "แม่", "👩", "people"],
  ["dad", "พ่อ", "👨", "people"],
  ["father", "พ่อ", "👨", "people"],
  ["grandma", "ยาย", "👵", "people"],
  ["grandpa", "ตา", "👴", "people"],
  ["sister", "พี่สาวน้องสาว", "👧", "people"],
  ["brother", "พี่ชายน้องชาย", "👦", "people"],
  ["friend", "เพื่อน", "🤝", "people"],
  ["teacher", "ครู", "🧑‍🏫", "people"],
  ["doctor", "หมอ", "🧑‍⚕️", "people"],
  ["nurse", "พยาบาล", "🧑‍⚕️", "people"],
  ["family", "ครอบครัว", "👪", "people"],
  ["face", "หน้า", "🙂", "body"],
  ["hair", "ผม", "💇", "body"],
  ["head", "หัว", "🙂", "body"],
  ["eye", "ตา", "👁️", "body"],
  ["ear", "หู", "👂", "body"],
  ["nose", "จมูก", "👃", "body"],
  ["mouth", "ปาก", "👄", "body"],
  ["tooth", "ฟัน", "🦷", "body"],
  ["teeth", "ฟัน", "🦷", "body"],
  ["tongue", "ลิ้น", "👅", "body"],
  ["neck", "คอ", "🙂", "body"],
  ["shoulder", "ไหล่", "💪", "body"],
  ["arm", "แขน", "💪", "body"],
  ["hand", "มือ", "✋", "body"],
  ["finger", "นิ้ว", "☝️", "body"],
  ["thumb", "นิ้วโป้ง", "👍", "body"],
  ["leg", "ขา", "🦵", "body"],
  ["knee", "เข่า", "🦵", "body"],
  ["foot", "เท้า", "🦶", "body"],
  ["toe", "นิ้วเท้า", "🦶", "body"],
  ["tummy", "ท้อง", "🙂", "body"],
  ["heart", "หัวใจ", "❤️", "body"],
  ["shirt", "เสื้อ", "👕", "clothes"],
  ["pants", "กางเกง", "👖", "clothes"],
  ["shorts", "กางเกงขาสั้น", "🩳", "clothes"],
  ["dress", "ชุดกระโปรง", "👗", "clothes"],
  ["skirt", "กระโปรง", "👗", "clothes"],
  ["sock", "ถุงเท้า", "🧦", "clothes"],
  ["shoe", "รองเท้า", "👟", "clothes"],
  ["hat", "หมวก", "🧢", "clothes"],
  ["cap", "หมวกแก๊ป", "🧢", "clothes"],
  ["coat", "เสื้อโค้ต", "🧥", "clothes"],
  ["jacket", "เสื้อแจ็กเก็ต", "🧥", "clothes"],
  ["pajamas", "ชุดนอน", "👕", "clothes"],
  ["button", "กระดุม", "🔘", "clothes"],
  ["zipper", "ซิป", "🤐", "clothes"],
  ["apple", "แอปเปิล", "🍎", "food"],
  ["banana", "กล้วย", "🍌", "food"],
  ["orange", "ส้ม", "🍊", "food"],
  ["grape", "องุ่น", "🍇", "food"],
  ["mango", "มะม่วง", "🥭", "food"],
  ["melon", "เมลอน", "🍈", "food"],
  ["lemon", "เลมอน", "🍋", "food"],
  ["strawberry", "สตรอว์เบอร์รี", "🍓", "food"],
  ["blueberry", "บลูเบอร์รี", "🫐", "food"],
  ["peach", "พีช", "🍑", "food"],
  ["pear", "ลูกแพร์", "🍐", "food"],
  ["watermelon", "แตงโม", "🍉", "food"],
  ["carrot", "แครอท", "🥕", "food"],
  ["corn", "ข้าวโพด", "🌽", "food"],
  ["potato", "มันฝรั่ง", "🥔", "food"],
  ["tomato", "มะเขือเทศ", "🍅", "food"],
  ["rice", "ข้าว", "🍚", "food"],
  ["noodle", "บะหมี่", "🍜", "food"],
  ["bread", "ขนมปัง", "🍞", "food"],
  ["egg", "ไข่", "🥚", "food"],
  ["milk", "นม", "🥛", "food"],
  ["water", "น้ำ", "💧", "food"],
  ["juice", "น้ำผลไม้", "🧃", "food"],
  ["soup", "ซุป", "🍲", "food"],
  ["cake", "เค้ก", "🍰", "food"],
  ["cookie", "คุกกี้", "🍪", "food"],
  ["cracker", "แครกเกอร์", "🍪", "food"],
  ["cereal", "ซีเรียล", "🥣", "food"],
  ["cheese", "ชีส", "🧀", "food"],
  ["yogurt", "โยเกิร์ต", "🥣", "food"],
  ["ice cream", "ไอศกรีม", "🍦", "food"],
  ["spoon", "ช้อน", "🥄", "home"],
  ["fork", "ส้อม", "🍴", "home"],
  ["cup", "แก้ว", "🥤", "home"],
  ["bottle", "ขวด", "🍼", "home"],
  ["bowl", "ชาม", "🥣", "home"],
  ["plate", "จาน", "🍽️", "home"],
  ["chair", "เก้าอี้", "🪑", "home"],
  ["table", "โต๊ะ", "🪑", "home"],
  ["bed", "เตียง", "🛏️", "home"],
  ["pillow", "หมอน", "🛏️", "home"],
  ["blanket", "ผ้าห่ม", "🛏️", "home"],
  ["door", "ประตู", "🚪", "home"],
  ["window", "หน้าต่าง", "🪟", "home"],
  ["floor", "พื้น", "🏠", "home"],
  ["wall", "ผนัง", "🏠", "home"],
  ["lamp", "โคมไฟ", "💡", "home"],
  ["light", "ไฟ", "💡", "home"],
  ["clock", "นาฬิกา", "⏰", "home"],
  ["phone", "โทรศัพท์", "📱", "home"],
  ["key", "กุญแจ", "🔑", "home"],
  ["soap", "สบู่", "🧼", "home"],
  ["towel", "ผ้าเช็ดตัว", "🧺", "home"],
  ["bath", "อาบน้ำ", "🛁", "home"],
  ["toilet", "ห้องน้ำ", "🚽", "home"],
  ["brush", "แปรง", "🪥", "home"],
  ["toothbrush", "แปรงสีฟัน", "🪥", "home"],
  ["toy", "ของเล่น", "🧸", "toy"],
  ["ball", "ลูกบอล", "⚽", "toy"],
  ["block", "บล็อก", "🧱", "toy"],
  ["doll", "ตุ๊กตา", "🧸", "toy"],
  ["teddy", "ตุ๊กตาหมี", "🧸", "toy"],
  ["puzzle", "จิ๊กซอว์", "🧩", "toy"],
  ["kite", "ว่าว", "🪁", "toy"],
  ["bike", "จักรยาน", "🚲", "toy"],
  ["scooter", "สกูตเตอร์", "🛴", "toy"],
  ["truck", "รถบรรทุก", "🚚", "toy"],
  ["train", "รถไฟ", "🚂", "toy"],
  ["car", "รถ", "🚗", "toy"],
  ["rocket", "จรวด", "🚀", "toy"],
  ["robot", "หุ่นยนต์", "🤖", "toy"],
  ["drum", "กลอง", "🥁", "toy"],
  ["bell", "กระดิ่ง", "🔔", "toy"],
  ["book", "หนังสือ", "📚", "school"],
  ["paper", "กระดาษ", "📄", "school"],
  ["pencil", "ดินสอ", "✏️", "school"],
  ["pen", "ปากกา", "🖊️", "school"],
  ["crayon", "สีเทียน", "🖍️", "school"],
  ["marker", "ปากกาเมจิก", "🖊️", "school"],
  ["eraser", "ยางลบ", "🧽", "school"],
  ["ruler", "ไม้บรรทัด", "📏", "school"],
  ["scissors", "กรรไกร", "✂️", "school"],
  ["glue", "กาว", "🧴", "school"],
  ["bag", "กระเป๋า", "🎒", "school"],
  ["lunchbox", "กล่องข้าว", "🍱", "school"],
  ["school", "โรงเรียน", "🏫", "school"],
  ["classroom", "ห้องเรียน", "🏫", "school"],
  ["playground", "สนามเด็กเล่น", "🛝", "place"],
  ["slide", "สไลเดอร์", "🛝", "place"],
  ["swing", "ชิงช้า", "🛝", "place"],
  ["park", "สวนสาธารณะ", "🏞️", "place"],
  ["home", "บ้าน", "🏠", "place"],
  ["house", "บ้าน", "🏠", "place"],
  ["room", "ห้อง", "🏠", "place"],
  ["kitchen", "ครัว", "🍳", "place"],
  ["bathroom", "ห้องน้ำ", "🚽", "place"],
  ["bedroom", "ห้องนอน", "🛏️", "place"],
  ["garden", "สวน", "🌷", "place"],
  ["shop", "ร้านค้า", "🏪", "place"],
  ["market", "ตลาด", "🛒", "place"],
  ["hospital", "โรงพยาบาล", "🏥", "place"],
  ["road", "ถนน", "🛣️", "place"],
  ["car", "รถ", "🚗", "vehicle"],
  ["bus", "รถบัส", "🚌", "vehicle"],
  ["train", "รถไฟ", "🚂", "vehicle"],
  ["boat", "เรือ", "⛵", "vehicle"],
  ["plane", "เครื่องบิน", "✈️", "vehicle"],
  ["bike", "จักรยาน", "🚲", "vehicle"],
  ["taxi", "แท็กซี่", "🚕", "vehicle"],
  ["ambulance", "รถพยาบาล", "🚑", "vehicle"],
  ["fire truck", "รถดับเพลิง", "🚒", "vehicle"],
  ["cat", "แมว", "🐱", "animal"],
  ["dog", "หมา", "🐶", "animal"],
  ["fish", "ปลา", "🐟", "animal"],
  ["bird", "นก", "🐦", "animal"],
  ["duck", "เป็ด", "🦆", "animal"],
  ["chicken", "ไก่", "🐔", "animal"],
  ["chick", "ลูกเจี๊ยบ", "🐥", "animal"],
  ["cow", "วัว", "🐮", "animal"],
  ["pig", "หมู", "🐷", "animal"],
  ["sheep", "แกะ", "🐑", "animal"],
  ["goat", "แพะ", "🐐", "animal"],
  ["horse", "ม้า", "🐴", "animal"],
  ["rabbit", "กระต่าย", "🐰", "animal"],
  ["mouse", "หนู", "🐭", "animal"],
  ["frog", "กบ", "🐸", "animal"],
  ["bee", "ผึ้ง", "🐝", "animal"],
  ["butterfly", "ผีเสื้อ", "🦋", "animal"],
  ["snail", "หอยทาก", "🐌", "animal"],
  ["turtle", "เต่า", "🐢", "animal"],
  ["bear", "หมี", "🧸", "animal"],
  ["panda", "แพนด้า", "🐼", "animal"],
  ["lion", "สิงโต", "🦁", "animal"],
  ["tiger", "เสือ", "🐯", "animal"],
  ["elephant", "ช้าง", "🐘", "animal"],
  ["monkey", "ลิง", "🐵", "animal"],
  ["giraffe", "ยีราฟ", "🦒", "animal"],
  ["zebra", "ม้าลาย", "🦓", "animal"],
  ["sun", "พระอาทิตย์", "☀️", "nature"],
  ["moon", "พระจันทร์", "🌙", "nature"],
  ["star", "ดาว", "⭐", "nature"],
  ["cloud", "เมฆ", "☁️", "nature"],
  ["rain", "ฝน", "🌧️", "nature"],
  ["snow", "หิมะ", "❄️", "nature"],
  ["wind", "ลม", "🍃", "nature"],
  ["sky", "ท้องฟ้า", "🌤️", "nature"],
  ["tree", "ต้นไม้", "🌳", "nature"],
  ["flower", "ดอกไม้", "🌸", "nature"],
  ["leaf", "ใบไม้", "🍃", "nature"],
  ["grass", "หญ้า", "🌿", "nature"],
  ["seed", "เมล็ด", "🌱", "nature"],
  ["rock", "ก้อนหิน", "🪨", "nature"],
  ["sand", "ทราย", "🏖️", "nature"],
  ["sea", "ทะเล", "🌊", "nature"],
  ["beach", "ชายหาด", "🏖️", "nature"],
  ["run", "วิ่ง", "🏃", "action"],
  ["walk", "เดิน", "🚶", "action"],
  ["jump", "กระโดด", "🦘", "action"],
  ["hop", "กระโดดเบา ๆ", "🦘", "action"],
  ["dance", "เต้น", "💃", "action"],
  ["sing", "ร้องเพลง", "🎵", "action"],
  ["clap", "ปรบมือ", "👏", "action"],
  ["wave", "โบกมือ", "👋", "action"],
  ["hug", "กอด", "🤗", "action"],
  ["kiss", "จุ๊บ", "😘", "action"],
  ["eat", "กิน", "🍽️", "action"],
  ["drink", "ดื่ม", "🥤", "action"],
  ["sleep", "นอน", "😴", "action"],
  ["wake", "ตื่น", "⏰", "action"],
  ["wash", "ล้าง", "🧼", "action"],
  ["brush", "แปรง", "🪥", "action"],
  ["read", "อ่าน", "📖", "action"],
  ["draw", "วาด", "🖍️", "action"],
  ["paint", "ระบายสี", "🎨", "action"],
  ["write", "เขียน", "✏️", "action"],
  ["count", "นับ", "🔢", "action"],
  ["build", "ต่อของ", "🧱", "action"],
  ["play", "เล่น", "🧸", "action"],
  ["share", "แบ่งปัน", "🤝", "action"],
  ["clean", "ทำความสะอาด", "🧽", "action"],
  ["open", "เปิด", "🚪", "action"],
  ["close", "ปิด", "🚪", "action"],
  ["push", "ดัน", "👉", "action"],
  ["pull", "ดึง", "👈", "action"],
  ["happy", "ดีใจ", "😊", "feeling"],
  ["sad", "เสียใจ", "😢", "feeling"],
  ["angry", "โกรธ", "😠", "feeling"],
  ["scared", "กลัว", "😨", "feeling"],
  ["sleepy", "ง่วง", "😴", "feeling"],
  ["hungry", "หิว", "😋", "feeling"],
  ["thirsty", "กระหายน้ำ", "🥤", "feeling"],
  ["tired", "เหนื่อย", "😮‍💨", "feeling"],
  ["sick", "ป่วย", "🤒", "feeling"],
  ["kind", "ใจดี", "💛", "feeling"],
  ["brave", "กล้าหาญ", "💪", "feeling"],
  ["fun", "สนุก", "🎉", "feeling"],
  ["red", "สีแดง", "🔴", "color"],
  ["blue", "สีน้ำเงิน", "🔵", "color"],
  ["green", "สีเขียว", "🟢", "color"],
  ["yellow", "สีเหลือง", "🟡", "color"],
  ["pink", "สีชมพู", "🌸", "color"],
  ["purple", "สีม่วง", "🟣", "color"],
  ["orange", "สีส้ม", "🟠", "color"],
  ["brown", "สีน้ำตาล", "🟤", "color"],
  ["black", "สีดำ", "⚫", "color"],
  ["white", "สีขาว", "⚪", "color"],
  ["gray", "สีเทา", "🩶", "color"],
  ["gold", "สีทอง", "⭐", "color"],
  ["circle", "วงกลม", "⭕", "shape"],
  ["square", "สี่เหลี่ยม", "⬛", "shape"],
  ["triangle", "สามเหลี่ยม", "🔺", "shape"],
  ["star shape", "รูปดาว", "⭐", "shape"],
  ["heart shape", "รูปหัวใจ", "❤️", "shape"],
  ["line", "เส้น", "➖", "shape"],
  ["dot", "จุด", "⚫", "shape"],
  ["big", "ใหญ่", "🔎", "concept"],
  ["small", "เล็ก", "🔍", "concept"],
  ["little", "เล็ก", "🔍", "concept"],
  ["tall", "สูง", "📏", "concept"],
  ["short", "สั้น", "📏", "concept"],
  ["long", "ยาว", "📏", "concept"],
  ["hot", "ร้อน", "🔥", "concept"],
  ["cold", "เย็น", "🧊", "concept"],
  ["wet", "เปียก", "💧", "concept"],
  ["dry", "แห้ง", "☀️", "concept"],
  ["fast", "เร็ว", "💨", "concept"],
  ["slow", "ช้า", "🐢", "concept"],
  ["up", "ขึ้น", "⬆️", "concept"],
  ["down", "ลง", "⬇️", "concept"],
  ["in", "ข้างใน", "📥", "concept"],
  ["out", "ข้างนอก", "📤", "concept"],
  ["one", "หนึ่ง", "1️⃣", "number"],
  ["two", "สอง", "2️⃣", "number"],
  ["three", "สาม", "3️⃣", "number"],
  ["four", "สี่", "4️⃣", "number"],
  ["five", "ห้า", "5️⃣", "number"],
  ["six", "หก", "6️⃣", "number"],
  ["seven", "เจ็ด", "7️⃣", "number"],
  ["eight", "แปด", "8️⃣", "number"],
  ["nine", "เก้า", "9️⃣", "number"],
  ["ten", "สิบ", "🔟", "number"]
];

const clean = (value: string) => value.toLowerCase().replace(/[^a-z]/g, "");

function makeHints(word: string): string[] {
  const compact = clean(word);
  const chunks = word.toLowerCase().split(/\s+/).map(clean).filter(Boolean);
  const hints = new Set<string>([compact, ...chunks]);

  if (compact.length > 2) hints.add(compact.slice(0, -1));
  if (compact.length > 3) hints.add(compact.slice(1));
  if (chunks.length > 1) hints.add(chunks.map(chunk => chunk[0]).join(""));

  return [...hints].slice(0, 5);
}

export function buildExpandedWords(): KidWord[] {
  return rawWords.map(([word, thai, emoji, category]) => ({
    word,
    thai,
    emoji,
    hints: makeHints(word),
    imagePrompt: `simple child-friendly flashcard for ${word}, real-life ${category} vocabulary, soft bright toy style, transparent background`
  }));
}
