import type { KidWord } from "./words";

type SupplementalWord = [word: string, thai: string, category: string];

const supplementalWords: SupplementalWord[] = [
  ["about", "เกี่ยวกับ", "general"],
  ["above", "ข้างบน", "general"],
  ["across", "ข้าม", "general"],
  ["add", "เพิ่ม", "general"],
  ["afraid", "กลัว", "feeling"],
  ["after", "หลังจาก", "time"],
  ["again", "อีกครั้ง", "general"],
  ["age", "อายุ", "general"],
  ["air", "อากาศ", "nature"],
  ["alive", "มีชีวิต", "general"],
  ["almost", "เกือบ", "general"],
  ["alone", "คนเดียว", "feeling"],
  ["along", "ไปตาม", "general"],
  ["already", "แล้ว", "time"],
  ["also", "ด้วย", "general"],
  ["always", "เสมอ", "time"],
  ["amazing", "น่าทึ่ง", "feeling"],
  ["answer", "คำตอบ", "school"],
  ["any", "อะไรก็ได้", "general"],
  ["anyone", "ใครก็ได้", "people"],
  ["anything", "อะไรก็ได้", "general"],
  ["area", "พื้นที่", "place"],
  ["around", "รอบ ๆ", "place"],
  ["ask", "ถาม", "action"],
  ["aunt", "ป้า", "people"],
  ["away", "ห่างออกไป", "place"],
  ["back", "หลัง", "body"],
  ["bad", "ไม่ดี", "concept"],
  ["bake", "อบ", "action"],
  ["bank", "ธนาคาร", "place"],
  ["basket", "ตะกร้า", "home"],
  ["bean", "ถั่ว", "food"],
  ["because", "เพราะว่า", "general"],
  ["before", "ก่อน", "time"],
  ["behind", "ข้างหลัง", "place"],
  ["better", "ดีกว่า", "concept"],
  ["between", "ระหว่าง", "place"],
  ["birthday", "วันเกิด", "time"],
  ["bit", "นิดหน่อย", "general"],
  ["blackboard", "กระดานดำ", "school"],
  ["bluebird", "นกสีฟ้า", "animal"],
  ["bone", "กระดูก", "body"],
  ["boot", "รองเท้าบูท", "clothes"],
  ["bored", "เบื่อ", "feeling"],
  ["bottom", "ด้านล่าง", "place"],
  ["branch", "กิ่งไม้", "nature"],
  ["break", "แตก", "action"],
  ["breakfast", "อาหารเช้า", "food"],
  ["bright", "สว่าง", "concept"],
  ["broom", "ไม้กวาด", "home"],
  ["bubble", "ฟอง", "toy"],
  ["bucket", "ถัง", "home"],
  ["bug", "แมลง", "animal"],
  ["building", "อาคาร", "place"],
  ["bunny", "กระต่าย", "animal"],
  ["busy", "ยุ่ง", "concept"],
  ["butter", "เนย", "food"],
  ["cabin", "กระท่อม", "place"],
  ["cage", "กรง", "home"],
  ["camera", "กล้อง", "home"],
  ["camp", "แคมป์", "place"],
  ["candy", "ลูกอม", "food"],
  ["care", "ดูแล", "action"],
  ["careful", "ระวัง", "concept"],
  ["cart", "รถเข็น", "home"],
  ["cash", "เงินสด", "general"],
  ["castle", "ปราสาท", "place"],
  ["cave", "ถ้ำ", "place"],
  ["cent", "เซนต์", "general"],
  ["center", "ตรงกลาง", "place"],
  ["change", "เปลี่ยน", "action"],
  ["cheer", "เชียร์", "action"],
  ["chin", "คาง", "body"],
  ["church", "โบสถ์", "place"],
  ["city", "เมือง", "place"],
  ["class", "ชั้นเรียน", "school"],
  ["clay", "ดินปั้น", "toy"],
  ["clear", "ชัดเจน", "concept"],
  ["climb", "ปีน", "action"],
  ["clip", "คลิป", "school"],
  ["closet", "ตู้เสื้อผ้า", "home"],
  ["cloth", "ผ้า", "home"],
  ["club", "ชมรม", "school"],
  ["coach", "ครูฝึก", "people"],
  ["coin", "เหรียญ", "general"],
  ["comb", "หวี", "home"],
  ["comfortable", "สบาย", "feeling"],
  ["corner", "มุม", "place"],
  ["couch", "โซฟา", "home"],
  ["country", "ประเทศ", "place"],
  ["cousin", "ลูกพี่ลูกน้อง", "people"],
  ["cover", "ปิดคลุม", "action"],
  ["crab", "ปู", "animal"],
  ["crack", "รอยแตก", "concept"],
  ["crawl", "คลาน", "action"],
  ["cross", "ข้าม", "action"],
  ["cucumber", "แตงกวา", "food"],
  ["curious", "อยากรู้", "feeling"],
  ["curtain", "ผ้าม่าน", "home"],
  ["cute", "น่ารัก", "concept"],
  ["daddy", "พ่อ", "people"],
  ["danger", "อันตราย", "concept"],
  ["dark", "มืด", "concept"],
  ["deep", "ลึก", "concept"],
  ["desk", "โต๊ะเรียน", "school"],
  ["diamond", "เพชร", "shape"],
  ["dinner", "อาหารเย็น", "food"],
  ["dirty", "สกปรก", "concept"],
  ["dish", "จาน", "home"],
  ["dream", "ฝัน", "feeling"],
  ["drop", "หยด", "action"],
  ["dust", "ฝุ่น", "home"],
  ["eagle", "นกอินทรี", "animal"],
  ["early", "เช้า", "time"],
  ["earth", "โลก", "nature"],
  ["east", "ทิศตะวันออก", "place"],
  ["easy", "ง่าย", "concept"],
  ["edge", "ขอบ", "place"],
  ["empty", "ว่างเปล่า", "concept"],
  ["end", "จบ", "time"],
  ["engine", "เครื่องยนต์", "vehicle"],
  ["enough", "พอ", "concept"],
  ["enter", "เข้า", "action"],
  ["evening", "เย็น", "time"],
  ["every", "ทุก", "general"],
  ["excited", "ตื่นเต้น", "feeling"],
  ["exit", "ทางออก", "place"],
  ["extra", "เพิ่ม", "general"],
  ["eyebrow", "คิ้ว", "body"],
  ["fair", "ยุติธรรม", "concept"],
  ["fall", "ล้ม", "action"],
  ["fan", "พัดลม", "home"],
  ["far", "ไกล", "place"],
  ["farm", "ฟาร์ม", "place"],
  ["farmer", "ชาวนา", "people"],
  ["feather", "ขนนก", "nature"],
  ["fence", "รั้ว", "place"],
  ["field", "ทุ่ง", "place"],
  ["fight", "ต่อสู้", "action"],
  ["fill", "เติม", "action"],
  ["fine", "สบายดี", "feeling"],
  ["finish", "เสร็จ", "action"],
  ["fire", "ไฟ", "nature"],
  ["flag", "ธง", "school"],
  ["flat", "แบน", "shape"],
  ["float", "ลอย", "action"],
  ["fluffy", "ฟูนุ่ม", "concept"],
  ["fly", "บิน", "action"],
  ["foam", "โฟม", "home"],
  ["forest", "ป่า", "place"],
  ["forget", "ลืม", "action"],
  ["fresh", "สด", "concept"],
  ["front", "ด้านหน้า", "place"],
  ["frown", "หน้าบึ้ง", "feeling"],
  ["full", "เต็ม", "concept"],
  ["gate", "ประตูรั้ว", "place"],
  ["gentle", "อ่อนโยน", "concept"],
  ["gift", "ของขวัญ", "home"],
  ["glass", "แก้ว", "home"],
  ["glove", "ถุงมือ", "clothes"],
  ["good", "ดี", "concept"],
  ["goose", "ห่าน", "animal"],
  ["great", "ยอดเยี่ยม", "concept"],
  ["ground", "พื้นดิน", "nature"],
  ["guess", "เดา", "action"],
  ["gum", "หมากฝรั่ง", "food"],
  ["gym", "โรงยิม", "place"],
  ["hamburger", "แฮมเบอร์เกอร์", "food"],
  ["hammer", "ค้อน", "home"],
  ["hard", "แข็ง", "concept"],
  ["healthy", "สุขภาพดี", "health"],
  ["hear", "ได้ยิน", "action"],
  ["heavy", "หนัก", "concept"],
  ["help", "ช่วย", "action"],
  ["hide", "ซ่อน", "action"],
  ["high", "สูง", "concept"],
  ["hill", "เนินเขา", "nature"],
  ["hole", "รู", "shape"],
  ["honey", "น้ำผึ้ง", "food"],
  ["hood", "ฮู้ด", "clothes"],
  ["hoop", "ห่วง", "toy"],
  ["hope", "หวัง", "feeling"],
  ["hose", "สายยาง", "home"],
  ["hungry", "หิว", "feeling"],
  ["idea", "ความคิด", "general"],
  ["important", "สำคัญ", "concept"],
  ["inside", "ข้างใน", "place"],
  ["iron", "เตารีด", "home"],
  ["island", "เกาะ", "place"],
  ["jeans", "ยีนส์", "clothes"],
  ["jog", "วิ่งเหยาะ", "action"],
  ["joke", "เรื่องตลก", "feeling"],
  ["joy", "ความสุข", "feeling"],
  ["keep", "เก็บไว้", "action"],
  ["king", "ราชา", "people"],
  ["kiss", "จุ๊บ", "action"],
  ["kitten", "ลูกแมว", "animal"],
  ["lady", "ผู้หญิง", "people"],
  ["lake", "ทะเลสาบ", "nature"],
  ["late", "สาย", "time"],
  ["laugh", "หัวเราะ", "action"],
  ["laundry", "ซักผ้า", "home"],
  ["left", "ซ้าย", "place"],
  ["lesson", "บทเรียน", "school"],
  ["lid", "ฝา", "home"],
  ["lift", "ยก", "action"],
  ["list", "รายการ", "school"],
  ["lizard", "กิ้งก่า", "animal"],
  ["loud", "ดัง", "sound"],
  ["lunch", "อาหารกลางวัน", "food"],
  ["mad", "โกรธ", "feeling"],
  ["mail", "จดหมาย", "home"],
  ["map", "แผนที่", "school"],
  ["mask", "หน้ากาก", "health"],
  ["match", "จับคู่", "school"],
  ["meal", "มื้ออาหาร", "food"],
  ["mess", "รก", "home"],
  ["middle", "ตรงกลาง", "place"],
  ["minute", "นาที", "time"],
  ["mirror", "กระจก", "home"],
  ["mistake", "ความผิดพลาด", "school"],
  ["money", "เงิน", "general"],
  ["monster", "สัตว์ประหลาด", "toy"],
  ["morning", "ตอนเช้า", "time"],
  ["mountain", "ภูเขา", "nature"],
  ["mud", "โคลน", "nature"],
  ["muffin", "มัฟฟิน", "food"],
  ["music", "ดนตรี", "sound"],
  ["nap", "งีบ", "time"],
  ["near", "ใกล้", "place"],
  ["neat", "เรียบร้อย", "concept"],
  ["need", "ต้องการ", "general"],
  ["new", "ใหม่", "concept"],
  ["newspaper", "หนังสือพิมพ์", "home"],
  ["nice", "ดี", "concept"],
  ["night", "กลางคืน", "time"],
  ["north", "ทิศเหนือ", "place"],
  ["note", "โน้ต", "school"],
  ["office", "สำนักงาน", "place"],
  ["oil", "น้ำมัน", "home"],
  ["old", "เก่า", "concept"],
  ["once", "ครั้งหนึ่ง", "time"],
  ["outside", "ข้างนอก", "place"],
  ["oval", "วงรี", "shape"],
  ["pack", "เก็บใส่", "action"],
  ["page", "หน้า", "school"],
  ["pair", "คู่", "general"],
  ["pancake", "แพนเค้ก", "food"],
  ["parent", "ผู้ปกครอง", "people"],
  ["party", "งานเลี้ยง", "time"],
  ["paste", "กาว", "school"],
  ["path", "ทางเดิน", "place"],
  ["peanut", "ถั่วลิสง", "food"],
  ["penguin", "เพนกวิน", "animal"],
  ["person", "คน", "people"],
  ["pet", "สัตว์เลี้ยง", "animal"],
  ["pickle", "แตงกวาดอง", "food"],
  ["pie", "พาย", "food"],
  ["pizza", "พิซซ่า", "food"],
  ["plant", "ต้นไม้", "nature"],
  ["plastic", "พลาสติก", "home"],
  ["pocket", "กระเป๋าเสื้อ", "clothes"],
  ["pond", "บ่อน้ำ", "nature"],
  ["popcorn", "ป๊อปคอร์น", "food"],
  ["porch", "ระเบียง", "home"],
  ["present", "ของขวัญ", "home"],
  ["pretend", "แกล้งทำ", "action"],
  ["proud", "ภูมิใจ", "feeling"],
  ["puppy", "ลูกหมา", "animal"],
  ["quietly", "อย่างเงียบ ๆ", "sound"],
  ["radio", "วิทยุ", "home"],
  ["rainbow", "รุ้ง", "nature"],
  ["rake", "คราด", "home"],
  ["ready", "พร้อม", "concept"],
  ["real", "จริง", "concept"],
  ["remember", "จำได้", "action"],
  ["rest", "พัก", "action"],
  ["ribbon", "ริบบิ้น", "home"],
  ["right", "ขวา", "place"],
  ["river", "แม่น้ำ", "nature"],
  ["roof", "หลังคา", "home"],
  ["rope", "เชือก", "toy"],
  ["safe", "ปลอดภัย", "concept"],
  ["salad", "สลัด", "food"],
  ["same", "เหมือนกัน", "concept"],
  ["sandwich", "แซนด์วิช", "food"],
  ["scarf", "ผ้าพันคอ", "clothes"],
  ["scary", "น่ากลัว", "feeling"],
  ["screen", "หน้าจอ", "home"],
  ["seat", "ที่นั่ง", "home"],
  ["secret", "ความลับ", "general"],
  ["self", "ตัวเอง", "people"],
  ["send", "ส่ง", "action"],
  ["shadow", "เงา", "nature"],
  ["shampoo", "แชมพู", "home"],
  ["sharp", "คม", "concept"],
  ["shelf", "ชั้นวาง", "home"],
  ["ship", "เรือใหญ่", "vehicle"],
  ["shopper", "คนซื้อของ", "people"],
  ["shout", "ตะโกน", "sound"],
  ["shovel", "พลั่ว", "home"],
  ["silly", "ตลก", "feeling"],
  ["sink", "อ่างล้างมือ", "home"],
  ["skip", "กระโดดข้าม", "action"],
  ["skunk", "สกังก์", "animal"],
  ["sled", "เลื่อนหิมะ", "toy"],
  ["slice", "ชิ้น", "food"],
  ["slipper", "รองเท้าแตะ", "clothes"],
  ["smooth", "เรียบ", "concept"],
  ["snake", "งู", "animal"],
  ["snack", "ของว่าง", "food"],
  ["sneeze", "จาม", "health"],
  ["soccer", "ฟุตบอล", "toy"],
  ["softly", "เบา ๆ", "sound"],
  ["south", "ทิศใต้", "place"],
  ["space", "อวกาศ", "nature"],
  ["spider", "แมงมุม", "animal"],
  ["spin", "หมุน", "action"],
  ["splash", "สาดน้ำ", "action"],
  ["spot", "จุด", "shape"],
  ["stairs", "บันได", "home"],
  ["stamp", "แสตมป์", "school"],
  ["stand", "ยืน", "action"],
  ["station", "สถานี", "place"],
  ["steam", "ไอน้ำ", "nature"],
  ["step", "ก้าว", "action"],
  ["sticker", "สติกเกอร์", "school"],
  ["stone", "หิน", "nature"],
  ["store", "ร้าน", "place"],
  ["storm", "พายุ", "weather"],
  ["story", "เรื่องเล่า", "school"],
  ["straight", "ตรง", "shape"],
  ["strange", "แปลก", "concept"],
  ["strong", "แข็งแรง", "concept"],
  ["stuck", "ติด", "concept"],
  ["sugar", "น้ำตาล", "food"],
  ["surprise", "แปลกใจ", "feeling"],
  ["sweet", "หวาน", "food"],
  ["tail", "หาง", "animal"],
  ["tape", "เทป", "school"],
  ["team", "ทีม", "people"],
  ["tent", "เต็นท์", "place"],
  ["thank", "ขอบคุณ", "general"],
  ["thin", "บาง", "concept"],
  ["ticket", "ตั๋ว", "general"],
  ["tidy", "เรียบร้อย", "concept"],
  ["tiny", "จิ๋ว", "concept"],
  ["toast", "ขนมปังปิ้ง", "food"],
  ["tomorrow", "พรุ่งนี้", "time"],
  ["tool", "เครื่องมือ", "home"],
  ["top", "ด้านบน", "place"],
  ["town", "เมือง", "place"],
  ["track", "ราง", "vehicle"],
  ["trash", "ขยะ", "home"],
  ["tray", "ถาด", "home"],
  ["treat", "ของกินพิเศษ", "food"],
  ["tunnel", "อุโมงค์", "place"],
  ["turkey", "ไก่งวง", "animal"],
  ["unclean", "ไม่สะอาด", "concept"],
  ["unlock", "ปลดล็อก", "action"],
  ["usual", "ปกติ", "general"],
  ["valley", "หุบเขา", "nature"],
  ["video", "วิดีโอ", "home"],
  ["visit", "เยี่ยม", "action"],
  ["voice", "เสียง", "sound"],
  ["wait", "รอ", "action"],
  ["warm", "อุ่น", "concept"],
  ["watch", "ดู", "action"],
  ["weak", "อ่อนแรง", "concept"],
  ["week", "สัปดาห์", "time"],
  ["west", "ทิศตะวันตก", "place"],
  ["wheel", "ล้อ", "vehicle"],
  ["whisper", "กระซิบ", "sound"],
  ["whole", "ทั้งหมด", "concept"],
  ["wide", "กว้าง", "concept"],
  ["wild", "ป่า", "nature"],
  ["wish", "ขอพร", "feeling"],
  ["wood", "ไม้", "nature"],
  ["worry", "กังวล", "feeling"],
  ["yardstick", "ไม้บรรทัดยาว", "school"],
  ["yesterday", "เมื่อวาน", "time"],
  ["young", "อายุน้อย", "people"],
  ["zip", "รูดซิป", "action"]
];

const englishOnlyCommonWords = `
accept achieve act action active activity actor adult advice afternoon ahead airport album alphabet animal apartment appear arrive art artist asleep
attic autumn avocado awake award awesome backyard badge bakery balcony balloon band barber baseball bathroom beach beanbag bedroom begin bicycle
blank blush board bookstore bounce bracelet brain brave bridge broccoli broken calendar calm camper candle cardboard cartoon cash register chalk
cheek chef cherry chess chest choice circle circus cleaner clockwork coatroom coconut coffee color cook corner costume cotton cream crown dancer
date deer dentist dessert diary dice dinosaur direction donut drawing driveway elevator energy envelope event exam exercise factory fairy fasten
favorite feather file flashlight folder football fountain freezer garage gasoline giant glitter globe golf grown guitar hallway helmet holiday
homework hospital hotel inch jacket jungle keyboard kindness ladder ladybug language library lunchroom magnet mailbox marble medicine memory menu
microscope midnight monkey movie museum napkin noodle notebook number ocean onion oven painter parking peach pear pepper photo picnic planet
playroom pocket police pool potato princess prize program pumpkin radio rectangle recycle refrigerator rescue restaurant rocket room ruler
sandbox sauce schoolbus season seatbelt shampoo shape shelter shopping sidewalk silver singer skateboard snowboard soap soccer spaceship spoonful
sprinkle stadium station string suitcase sunset supermarket sweater tablet teacup telephone television theater thermometer thunder toothbrush
tornado tractor traffic travel treasure trumpet turtle uncle uniform vacation vegetable visitor wagon waterfall weekend worksheet workshop zipper
able absent accident account address adventure agree ahead airport alarm alert allow animal answer anywhere arrow author badge balance basic
believe belong bend bicycle blanket blind borrow bottle brave bridge button cable captain careful chance chapter charity check circle citizen
clean clever collect combine comfort company compare complete concert connect control correct costume couple courage create crowd daily decide
degree deliver depend describe design detail different difficult discover divide dollar double dozen drawer eager earn effort either else enjoy
equal escape exact example explain explore fair famous fancy final follow forgive forward gentle giant guide habit happen helpful honest honor
include invite island judge kind know large learn level local lucky machine magic manage manner measure member message method minus moment
natural nervous normal notice often order owner page pattern pause peace perfect place plain point polite possible power prepare problem promise
proper protect public puzzle reason receive record repair repeat report result return reward rhythm search select service settle simple single
skill solid solve special square steady stretch subject success suggest support sure talent target task trouble trust truth useful value visitor
wonder actual afraid ahead amount animal appear arrive asleep attention avoid badge basic become begin below beside beyond borrow brave busy
camera capital careful carry center certain change choice collect color common compare complete copy corner daily danger decide deep describe
different dinner discover distance early earth easy empty enjoy evening excited expert family famous favorite field finish flower forest gentle
ground group healthy history holiday idea inside interest join journey kitchen ladder language late laugh learn leave letter listen local lonely
machine matter measure meeting memory minute month mountain music narrow nature notice ocean parent pattern person picture planet quiet reach
really river round safety science season second secret sentence separate serious service shelter simple slowly special spring square station
summer surface teacher ticket together tomorrow travel village winter wonder worker world
`.trim().split(/\s+/);

const clean = (value: string) => value.toLowerCase().replace(/[^a-z]/g, "");

function makeHints(word: string): string[] {
  const compact = clean(word);
  const chunks = word.toLowerCase().split(/\s+/).map(clean).filter(Boolean);
  const hints = new Set<string>([compact, ...chunks]);

  if (compact.length > 2) hints.add(compact.slice(0, -1));
  if (compact.length > 3) hints.add(compact.slice(1));
  if (chunks.length > 1) hints.add(chunks.map(chunk => chunk[0]).join(""));

  return [...hints].slice(0, 5);
}

export function buildSupplementalWords(): KidWord[] {
  const translatedWords: KidWord[] = supplementalWords.map(([word, thai, category]) => ({
    word,
    thai,
    emoji: "?",
    tier: "general" as const,
    priority: -0.12,
    hints: makeHints(word),
    imagePrompt: `simple child-friendly flashcard for ${word}, common ${category} vocabulary, soft bright toy style, transparent background`
  }));

  const translatedKeys = new Set(translatedWords.map(item => clean(item.word)));
  const englishOnlyWords = englishOnlyCommonWords
    .filter(word => !translatedKeys.has(clean(word)))
    .map(word => ({
      word,
      thai: word,
      emoji: "?",
      tier: "general" as const,
      priority: -0.2,
      hints: makeHints(word),
      imagePrompt: `simple child-friendly flashcard for ${word}, common English vocabulary, soft bright toy style, transparent background`
    }));

  return [...translatedWords, ...englishOnlyWords];
}
